CDCgov/ixa-epi-isolation

Cargo.toml, src/parameters_loader.rs, src/population_loader.rs
Suggesting some changes to how we are reading the population and for the test. I think we should try census tract as a person property, at least for now.
=> Gce pop loader fix tract

Cargo.toml, src/contact.rs, src/main.rs, src/parameters.rs, src/transmission_manager.rs
This PR implements a skeleton of the transmission model described in `docs/transmission.md`. The focus is not on getting the math right but rather the workflow of how we want to write our transmission model.
This implements a simple way to get contacts (with test) and a simple person-to-person transmission based on some generation interval.
- What do you think of the general structuring of functions?
- Places where more test coverage is necessary?
- The overall logic/flow?
=> Skeleton of transmission model

.gitignore, scripts/create_synthetic_population.R
This PR includes a script to generate synthetic populations. The algorithm samples houses from the census datasets available in pums based on the household weight and the desired population size. Region coordinates are downloaded for each region based on their PUMA codes. These coordinates are then assigned to each house based on their PUMA code. Finally, two files are generated: people (age, home_id), and region (region_id, lat, lon). Region id is generated as follows: 2 digits for state, 9 digits for PUMA code. Home id is region id + 6 digits that represent the home number.
Census tracts have been changed to region id in the ixa code. 
These populations are for testing purposes only.
=> Simple synthetic population generator 

input/input.json, scripts/plot_outputs.R, src/main.rs, src/parameters.rs, src/transmission_manager.rs
Merging both reports into one. I'm also removing unused parameters related to the reports.
=> Gce report fix

docs/0 contents.md, docs/time-varying-infectiousness.md
This PR adds just a readme that describes an approach for modeling an arbitrary infectious period using order statistics. The focus of this document is explaining the need for this particular approach and a brief description of the math, not code.
Any and all feedback is welcome. I welcome particular feedback on the explanations of rejection sampling. Please also let me know any sections you think need to be more fleshed out.
This PR will not be merged in until all relevant parties have gotten the relevant time to review.
Cargo build/test will fail because the version of our code on main does not compile with the latest updates to ixa, in particular the need for `IxaError` in `define_global_properties!` with the new addition of a validator. However, there is a PR in place to fix that, and …
=> Describing our approach to modeling an arbitrary infectiousness distribution

.github/workflows/build-test.yaml, README.md, src/contact.rs, src/main.rs, src/parameters.rs, src/population_loader.rs, src/transmission_manager.rs
As described in issue #28, removed unnecessary module name in ixa imports, updated main to use ixa runner with custom args, and use `sample_person`. A couple of things to highlight:
1) sample_person does not yet allow to filter by a person property, so making a safe assumption here that everyone is alive at time t = 0.
2) It's a bit confusing to use custom_args for boolean values. For instance, I used the `force_overwrite` flag to determine whether or not to overwrite reports. If not specified, I would assume the value is false, but if not specified, `custom_args` would not exist, so I still need to do `if let Some(custom_args) = custom_args {}else{}`, which seems a bit unnecessasry.
=> Update ixa - Closes issue #28

src/main.rs, src/transmission_manager.rs
Removed the need to use custom arguments to use force overwrite
=> Gce ixa runner nocustom

.github/workflows/pre-commit.yaml, .pre-commit-config.yaml
Not sure why CI in #41 didn't complain that the pre-commit workflow needed packages cached. When I include this commit in #40, pre-commit on Github Actions passes. While I was at it, I updated the styler and used ruff over black in line with the current CFA repo template.
=> Update Github actions precommit workflow

input/input.json, src/infection_propagation_loop.rs, src/infectiousness_manager.rs, src/main.rs, src/parameters.rs, src/population_loader.rs
This is just a small utility to make getting parameter values a little cleaner and replaces a bunch of `unwrap`s everywhere (which kind of suck without a `message`) 
I also added a test for the default config file that will fail if we forget to update it.
=> Add get_params utility

src/infection_propagation_loop.rs, src/infectiousness_manager.rs
"Infectious" implies that the person is capable of transmitting disease while "infected" simply says that the person has succumbed to infection. We are interested in when people transmit disease (which may be disconnected from when they "recover" in terms of symptoms), so we want to use "infectious" to better indicate that this status refers to people who are actively capable of infecting others, regardless of their other clinical statuses.
=> Change `InfectionStatusValue::Infected` to be `InfectionStatusValue::Infectious`

src/infection_propagation_loop.rs
This is inspired by the tests we had the previous transmission manager (see #51's deleted files) but welcome suggestions for other statistical tests to include.
=> Add statistical tests for infection loop. Closes #52.

src/infection_propagation_loop.rs, src/rate_fns/constant_rate.rs, src/rate_fns/empirical_rate.rs, src/rate_fns/rate_fn.rs, src/rate_fns/rate_fn_storage.rs
- Although infection duration is still specified as a global parameter, this structure enables each rate function type to have their own definition of infection duration and for each rate function instance to have a different value of the infection duration.
- If we switch to the structure in #62, infection duration can be specified for each rate function at input.
- This PR does not solve the problem of needing to model _symptom_ recovery, and a subsequent PR will introduce a `ClinicalDiseaseSymptomStatus` and tracker.
=> Integrate infection duration into `InfectiousnessRateFn`. Proposal to close #55.

src/infectiousness_manager.rs
The `assert!` evaluation in comparing the current infectiousness with forecasted infectiousness works for checking rounding errors but doesn't provide the actual panic check we want for the evaluation. Changed here to keep the evaluation consistent. This `assert!` still panics for some forecasts that possess rounding errors.
=> Made evaluate forecast assert statement match error message

.github/workflows/pre-commit.yaml, input/input.json, src/contact.rs, src/infection_propagation_loop.rs, src/infectiousness_manager.rs, src/main.rs, src/parameters.rs, src/population_loader.rs, src/rate_fns/rate_fn_storage.rs, src/settings.rs, src/transmission_report.rs
Integrating settings-based properties by including a global mixing helper function in test modules and defining a macro for implementing SettingType for arbitrary names. Includes adjustments to read in alpha values (and future `SettingProperties`) in the parameter input.json.
* Added a new `settings_properties` field to the `Params` struct to allow dynamic configuration of transmission modifiers for different settings (e.g., Home, Workplace, School, CensusTract). These draw from an introduced `enum` `CoreSettingsTypes` defined in the `settings.rs`
* Refactored `population_loader.rs` to remove hardcoded setting properties and ensure itineraries are dynamically created based on input parameters. Moved itinerary intialization into `settings.rs`
* Introduced the `global_mixing_itinerary` …
=> Make tests pass and read in alpha values for settings module

src/settings.rs
This PR introduces a validation method to check properties of a new itinerary. An existing check for duplicate itineraries has been added to this method and a new check for non-negative itinerary ratios has been added. A unit test checking the correct error is thrown for a negative itinerary ratio has been added.
=> Validate a new itinerary

src/rate_fns/rate_fn_storage.rs
In the `EmpiricalRateFnRecord` struct, the variable `id` was forced to be an 8-bit unsigned integer, which precluded simulations drawing from more than 256 empirical rate functions. This PR revises it to be a 32-bit unsigned integer.
=> increase allowable integers for ids

input/input.json, src/transmission_report.rs
- Refactored the `record_transmission_event` function and updated the event subscription logic to ensure proper handling of infection data.
- Added a new `transmission_report_name` parameter to specify the output file name for the transmission report.
=> Fixed transmission report

src/rate_fns/empirical_rate.rs
See #121 for details/description/problem.
=> Make empirical rates not extrapolate rate below the minimum provided time. Closes #121.

src/infection_propagation_loop.rs, src/infectiousness_manager.rs, src/settings.rs
This PR addresses three TODO statements documented in issues #103, #105, and #107. The checks largely involve examining the contents of the `SettingsDataContainer` to observe if setting types are registered. 
- A new trait extension, `validate_setting_registration` was added to validate setting type registration. 
- The `getting_setting_properties` trait extension is modified to return a `Result<SettingProperties, IxaError>
- Three new tests were added.
-  Is there a way to call `self.validate_setting_registration` from within `get_setting_properties`?
- Should the solution to issue #105 throw an `IxaError` or just return none? 
- This PR addresses an additional TODO statement documented in issue #114.
- The validation of settings requires that they be registered before individuals can be …
=> Setting validation 

src/infection_propagation_loop.rs, src/infectiousness_manager.rs, src/population_loader.rs, src/settings.rs
Don't fully love that we have to take a reference to a setting when making a new setting id, but this gets the job done of removing the tuple of specifying both `&dyn SettingType` and `id: usize` separately when needing the setting id.
=> Refactor places that require setting location to take `SettingId` rather than a tuple

src/infection_propagation_loop.rs
* Updated the `ixa` dependency from version `0.1.1` to `0.2.0` in `Cargo.toml` to incorporate the latest features and fixes.
* Replaced the use of `context.query_people` with `context.sample_people`, which directly samples a subset of susceptibles based on the calculated number (`n`)
- Previous implementation had the proportion being calculated on susceptibles remaining, meaning that seeding infections impacted the proportion of "recovered" in the population. Now `n` is strictly based on population size
=> Use `sample_people()` method

src/infection_propagation_loop.rs
Skip the initialization of changing status of susceptible individuals if the proportion to seed is zero. Was causing a sample error for a binomial with mean 0 otherwise. Added a trace statement when the number of individuals to seed is drawn for the population for each call of `query_susceptibles_and_seed`
=> Skip seed function if recovered or infection proportion is zero

src/infection_propagation_loop.rs
`sample_people` panics when sampling 0 people, so it should be skipped in the `query_susceptible_and_seed()` function if we randomly select 0 susceptibles to seed on the binomial draw
=> Don't call `sample_people` if k is not greater than 0

src/infection_propagation_loop.rs
The plans that need to be cancelled are handled by the event subscription. This will only cancel already-executed or already-cancelled plans.
=> Remove unnecessary plan cancellation

scripts/create_synthetic_population.R
Improve the sampling runtime for creating a synthetic population. Batch size dynamically adjusts based on the remaining population to be sampled. A cap of 2,000 households per batch is used, with an initial batch size of 30 for the first iteration to estimate average household size.
A faster approach would use `slice_sample(n=batch_size, weight_by=WGTP)`, but this would require a `many-to-many` join.
=> Dynamic batch size from avg household size

input/input.json, src/hospitalizations.rs, src/policies/updated_guidance.rs, src/symptom_progression.rs
This PR updates default `mean_delay_to_hospitalization` and `mean_duration_of_hospitalization` to 6 and 8 days respectively. The values were pulled from previous literature of model parameters in the [GCM experiment repo](https://github.com/cdcent/cfa-cmei-gcm-mvp-experiments/tree/etr_experiment_refactor/Documentation). 
People now begin the event sequence to enter the hospital once they start presenting with symptoms. The derived person property presenting with symptoms has been moved from the updated guidance to the symptom progression module.
=> Fixing hospital parameters and hospitalization event sequence

src/infection_propagation_loop.rs, src/infectiousness_manager.rs, src/population_loader.rs, src/settings.rs
Clarify the distinction between "current" and "total" infectiousness multipliers, and update the logic for handling itinerary entries and infection propagation using "activity" as a measure of presence. Ratios are adjusted to 0.0 instead of removing people as members from settings. The changes improve code clarity and correctness by using more precise function names and ensuring consistent handling of itinerary entry options.
**Changes**
* Replaced calls to `calculate_total_infectiousness_multiplier_for_person` with `calculate_current_infectiousness_multiplier_for_person` and `calculate_max_infectiousness_multiplier_for_person` in `src/infectiousness_manager.rs` that leverage active versus inactive membership counts.
* Reduced necessary checks for infector forecast plan changes in …
=> Track activity in settings in addition to membership for improved performance.

input/input.json, src/policies/mod.rs, src/policies/previous_guidance.rs, src/policies/updated_guidance.rs, src/symptom_progression.rs
This module implements the previous isolation guidance. This can be thought of a decision tree shown in the image below. The logic of the policy is handled my two separate methods `isolation` and `handle_symptom_resolution`
- `isolation`: set the individual to begin isolating and schedules a follow up test if necessary
- `handle_symptom_resolution`: at the time the symptoms of an individual end, depending on the individuals last test result and their symptom category, determines how long they should remain in isolation, and if they should follow post isolation pre caution. 
There are five tests for the policy. The first 3 tests infect a single person and observe their progression through the policy decision tree. It is likely that test 3 could be extended to capture tests 1 and 2, but for …
=> Implementing the previous isolation guidance

Cargo.toml, src/settings.rs
Replace data structures of `HashSet`, `Vec`, and `HashMap` for active members with `IndexSet` from the `indexmap` crate. Runtime and memory usage are nearly identical for this method and the custom `HashMap`/`Vec` approach, but is more readable and creates fewer redundant structures. 
**Changes**
* Added the `indexmap` crate as a dependency
* Replaced all uses of `HashSet`, `HashMap`, and `Vec` for setting members with `IndexSet` in `SettingDataContainer` and related methods, removing redundant containers and index-tracking logic.
=> Switch to `IndexSet` for tracking active members

Cargo.toml, src/hospitalizations.rs
Given the change in https://github.com/CDCgov/ixa/pull/510 it is now possible to have hospital age groups be a derived person property, this means we can remove the hospital data container which stored the age group mapping.
=> Hospital age groups derived person property

experiments/README.md
I've not added the jupyter install flag as this is issued by poetry if it cannot be installed automatically. jupyter is listed in the `pyproject.toml`
=> added detail to quarto section. Closes #273

input/input.json, src/parameters.rs, src/reports/incidence_report.rs, src/reports/mod.rs, src/reports/prevalence_report.rs, src/reports/transmission_report.rs
Switched from a vector of report enums to explicit, structured report parameters for each report type. 
**Changes**
* Replaces the `reports` vector of `ReportType` enums in `Params` with explicit fields for `prevalence_report`, `incidence_report`, and `transmission_report`, each using the new `ReportParams` struct. 
* Updates the JSON input format and test fixtures to use the new explicit report fields instead of the previous array-of-enums format. 
* Introduces the `ReportParams` struct, which includes `write`, `name`, and `period` fields, replacing the previous enum-based approach. Users can now use `"prevalence_report": {"write": false}` to drop the prevalence report, or keep the filename and period present while also setting to `false` to drop the report.
* Adds helper functions …
=> Remove `reports` vector
